apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: nagp-assignment
type: Opaque
data:
  DB_PASSWORD: bmFncHBhc3N3b3Jk
  POSTGRES_PASSWORD: bmFncHBhc3N3b3Jk
  POSTGRES_USER: bmFncHVzZXI=